# coding: utf-8

"""
    Compass - Request Tracker

    API documentation for Compass - Request Tracker. This document contains a complete list of fields for a Compass request accessible to an admin. An authorized user may only read, write, and update certain fields or delete based on their role. All requests require a valid OAuth2 Bearer Token passed as a header that is associated with a Cisco CEC user account.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: compass-devcx@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BulkPatchResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'updated_records': 'int',
        'total_records': 'int'
    }

    attribute_map = {
        'status': 'status',
        'updated_records': 'updatedRecords',
        'total_records': 'totalRecords'
    }

    def __init__(self, status=None, updated_records=None, total_records=None):  # noqa: E501
        """BulkPatchResponse - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._updated_records = None
        self._total_records = None
        self.discriminator = None
        self.status = status
        self.updated_records = updated_records
        self.total_records = total_records

    @property
    def status(self):
        """Gets the status of this BulkPatchResponse.  # noqa: E501


        :return: The status of this BulkPatchResponse.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this BulkPatchResponse.


        :param status: The status of this BulkPatchResponse.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501
        allowed_values = ["Success"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def updated_records(self):
        """Gets the updated_records of this BulkPatchResponse.  # noqa: E501


        :return: The updated_records of this BulkPatchResponse.  # noqa: E501
        :rtype: int
        """
        return self._updated_records

    @updated_records.setter
    def updated_records(self, updated_records):
        """Sets the updated_records of this BulkPatchResponse.


        :param updated_records: The updated_records of this BulkPatchResponse.  # noqa: E501
        :type: int
        """
        if updated_records is None:
            raise ValueError("Invalid value for `updated_records`, must not be `None`")  # noqa: E501

        self._updated_records = updated_records

    @property
    def total_records(self):
        """Gets the total_records of this BulkPatchResponse.  # noqa: E501


        :return: The total_records of this BulkPatchResponse.  # noqa: E501
        :rtype: int
        """
        return self._total_records

    @total_records.setter
    def total_records(self, total_records):
        """Sets the total_records of this BulkPatchResponse.


        :param total_records: The total_records of this BulkPatchResponse.  # noqa: E501
        :type: int
        """
        if total_records is None:
            raise ValueError("Invalid value for `total_records`, must not be `None`")  # noqa: E501

        self._total_records = total_records

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BulkPatchResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BulkPatchResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
