# coding: utf-8

"""
    Compass - Request Tracker

    API documentation for Compass - Request Tracker. This document contains a complete list of fields for a Compass request accessible to an admin. An authorized user may only read, write, and update certain fields or delete based on their role. All requests require a valid OAuth2 Bearer Token passed as a header that is associated with a Cisco CEC user account.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: compass-devcx@cisco.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ViewBaseColumns(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data': 'str',
        'active': 'bool',
        'index': 'int'
    }

    attribute_map = {
        'data': 'data',
        'active': 'active',
        'index': 'index'
    }

    def __init__(self, data=None, active=None, index=None):  # noqa: E501
        """ViewBaseColumns - a model defined in Swagger"""  # noqa: E501
        self._data = None
        self._active = None
        self._index = None
        self.discriminator = None
        if data is not None:
            self.data = data
        if active is not None:
            self.active = active
        if index is not None:
            self.index = index

    @property
    def data(self):
        """Gets the data of this ViewBaseColumns.  # noqa: E501


        :return: The data of this ViewBaseColumns.  # noqa: E501
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ViewBaseColumns.


        :param data: The data of this ViewBaseColumns.  # noqa: E501
        :type: str
        """

        self._data = data

    @property
    def active(self):
        """Gets the active of this ViewBaseColumns.  # noqa: E501


        :return: The active of this ViewBaseColumns.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this ViewBaseColumns.


        :param active: The active of this ViewBaseColumns.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def index(self):
        """Gets the index of this ViewBaseColumns.  # noqa: E501


        :return: The index of this ViewBaseColumns.  # noqa: E501
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this ViewBaseColumns.


        :param index: The index of this ViewBaseColumns.  # noqa: E501
        :type: int
        """

        self._index = index

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ViewBaseColumns, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ViewBaseColumns):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
